### PR TITLE
Add a bcrypt alphabet

### PR DESCRIPTION
**Pull request by Zireael-N**

### CODE REVIEW

**Comment by marshallpierce** [comment]
Thanks. One wonders what fever dream caused them to use a different character set to begin with...

**Comment by marshallpierce** [comment]
Released in 0.12.1.

**Comment by Zireael-N** [comment]
> One wonders what fever dream caused them to use a different character set to begin with...

I once had a pleasure of working with a base64 implementation that used N most significant bits where commonly N least significant bits were used and vice versa, that was an experience I don't think I'll ever forget.

**Comment by marshallpierce** [comment]
dear  god D:

**Pull request merged**
