### PR TITLE
Relaxed ?Sized requirement for decode and encode functions

### PR DESCRIPTION
**Pull request by frol**
It seems that the ?Sized requirement is redundant.

### CODE REVIEW

**Comment by frol** [comment]
NOTE: CI failure on nightly is not related to the PR changes. All tests just pass.

**Comment by marshallpierce** [comment]
Isn't `?Sized` _removing_ a constraint? https://doc.rust-lang.org/std/marker/trait.Sized.html

**Comment by frol** [comment]
It removes the constraint from the `T` (which is `AsRef<[u8]>`), but it enforces the reference (which is Sized), and this does not make as lot of sense with `AsRef` trait. Consider the following example:

```
fn qq1<T: AsRef<[u8]> + ?Sized>(_a: &T) {}

fn qq2<T: AsRef<[u8]>>(_a: T) {}

fn main() {
    let a = vec![1];
    qq1(&a);
    //qq1(a);  // <-- This does not compile
    qq2(&a);
    qq2(a);
}
```

I think `AsRef<[u8]>` is the same as `&(AsRef<[u8]> + ?Sized)`, but the latter has a restriction to pass by an explicit reference.

**Comment by marshallpierce** [comment]
Gotcha. I'll fix Travis.

**Comment by marshallpierce** [comment]
merge in `master`, and then this should be ready to go.

**Comment by frol** [comment]
@marshallpierce Done.

**Comment by marshallpierce** [comment]
Thanks!

**Pull request merged**
