### PR TITLE
Refactor/code quality

### PR DESCRIPTION
**Pull request by danieleades**

### CODE REVIEW

**Comment by marshallpierce** [comment]
Thanks for the cleanups. It'll be in the next release.

**Comment by hellow554** [comment]
Most of these changes come from clippy, I guess?

@marshallpierce what do you think of adding the following to your circle yaml?

```yml
- run:
          name: Check clippy lints
          command: |
            rustup component add clippy
            cargo clippy
```

**Comment by danieleades** [comment]
> Most of these changes come from clippy, I guess?
> 
> @marshallpierce what do you think of adding the following to your circle yaml?
> 
> ```yaml
> - run:
>           name: Check clippy lints
>           command: |
>             rustup component add clippy
>             cargo clippy
> ```

if you did this, you'd probably want the command to be `cargo clippy --all-targets`, so as to also lint the fuzz, unit test, and integration test targets.

**Comment by marshallpierce** [comment]
Thanks for the suggestions. Merged w/ CI clippy via #186.

**Pull request merged**
