### PR TITLE
Fix DecoderReader handling of padding

### LINKED ISSUE #226: DecoderReader accepts incorrect input
When parts read from underlying reader include valid padding the
reader accepts the input even if there’s more data to follow.  In this
example the reader produces string `AA==AA==AA==` which should result
in an error but instead generates three zero bytes.

```rust
struct Foo(usize);

impl std::io::Read for Foo {
    fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
        if self.0 == 0 {
            return Ok(0);
        }
        self.0 -= 1;
        buf[..4].copy_from_slice(b"AA==");
        Ok(4)
    }
}

fn main() {
    use std::io::Read;
    use base64::engine::general_purpose::STANDARD;

    let mut decoder = base64::read::DecoderReader::new(Foo(3), &STANDARD);
    let mut vec = Vec::new();
    let res = decoder.read_to_end(&mut vec);
    print!("{res:?} {vec:?}");
}
```

### PR DESCRIPTION
**Pull request by marshallpierce**
Fixes #226.

DecoderReader now keeps more state so that erroneous internal padding that happens to fall right on a read buffer boundary isn't silently ignored.

### CODE REVIEW

**Comment by danielabrozzoni** [comment]
Hey, is there any reason why this PR should update the crate MSRV? We're using `base64` in https://github.com/bitcoindevkit/rust-esplora-client and we'd like to keep 1.57.0 as our MSRV, but at the same time we would prefer not to pin base64 to "0.21.0" as we'd like to have this bug fix in. Thanks!

**Comment by marshallpierce** [comment]
Huh, I figured that was old enough most people won't care, but I can roll that back. 1.60 is needed to build the dev dependencies, but for the main code, 1.57 is still fine. I'll release another version with that change.

**Comment by danielabrozzoni** [comment]
That would be great! Thanks :)

**Comment by marshallpierce** [comment]
Fix incoming in https://github.com/marshallpierce/rust-base64/pull/239

**Pull request merged**
