### PR TITLE
expose encoded_size function

### PR DESCRIPTION
**Pull request by GallagherCommaJack**
solves #137

### CODE REVIEW

**Comment by marshallpierce** [comment]
Just curious -- what is your use case that the conservative 4/3 estimate doesn't address?

**Comment by Kerndog73** [comment]
Even though the math for the 4/3 estimate is incredibly simple, I still think that this should be added to the library. Despite its simplicity, I had to look it up to make sure I didn't mess up. A named function is better than math. It would be nice if this was `const` too.

**Comment by marshallpierce** [comment]
That's fair. Once I have a block of time to finish up the current in progress work (which may change its API a little) I'll make it public.

**Comment by marshallpierce** [comment]
Done in https://github.com/marshallpierce/rust-base64/pull/167.

**Pull request closed without merging**
